# Numpy

In [7]:
my_arr = [1,2,3]

In [8]:
my_arr

[1, 2, 3]

In [3]:
import numpy as np

In [8]:
np_arr = np.array(my_arr)

In [9]:
np_arr

array([1, 2, 3])

In [16]:
aa = np.arange(6)

In [17]:
aa

array([0, 1, 2, 3, 4, 5])

In [19]:
aa.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
D3_list = [[2,3,4],[6,4,8],[6,2,1]]

In [22]:
D3_list

[[2, 3, 4], [6, 4, 8], [6, 2, 1]]

In [23]:
# 2D  array as it is having 2 brackets at the starting 
np.array(D3_list)

array([[2, 3, 4],
       [6, 4, 8],
       [6, 2, 1]])

In [24]:
# an array which start at 2 and exclusion of 10 having step size 2
np.arange(2,10,2)

array([2, 4, 6, 8])

In [26]:
# if we want to generate an array having only zero's

np.zeros(3)

array([0., 0., 0.])

In [29]:
# pasing a tuple is we want any other dimentions
# (rows, column )
np.zeros((5,5)) 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
# if i want array of one
np.ones(5)

array([1., 1., 1., 1., 1.])

In [31]:
np.ones((3,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [32]:
# if we want the no. of values evenly spaced b/w two values
np.linspace(2,10,5)

array([ 2.,  4.,  6.,  8., 10.])

In [33]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [34]:
# CREATE an identity matrix using numpy (square matrix having digonal one 1 and other values is 0)
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [35]:
# to get the random value of normal distribution (b/w 0 to 1)
np.random.rand(5) #pass the no. of random values we want 

array([0.73472587, 0.76483393, 0.8196386 , 0.47727594, 0.33401286])

In [36]:
# now to get 2D array instead of passing as a tuple here we pass as an argument
np.random.rand(3,5)

array([[0.50901213, 0.52141522, 0.26053825, 0.71794276, 0.99153355],
       [0.03147197, 0.68636228, 0.31050822, 0.9436614 , 0.27355058],
       [0.85665568, 0.80550044, 0.18001241, 0.57540651, 0.73089381]])

In [37]:
# to get the random value from standard distribution (gussaian distribution)
np.random.randn(3)

array([ 0.88529377,  0.90592673, -2.17700003])

In [38]:
np.random.randn(2,3)

array([[ 0.75537269, -1.73049479,  0.90703526],
       [ 1.84844469,  1.08418792,  0.31488089]])

In [39]:
# to get a random integer from numpy
# here we pass low and high value and we get a value b/w them
np.random.randint(0,100)

48

In [40]:
# to get the no. of interger b/w the numbers
np.random.randint(0,100,3)

array([45, 31, 35])

In [42]:
# to reshape the array
np.random.randint(0,100,10).reshape(2,5) # the only thing we have to consider here is the no. of values in
#array = row * column in reshape function

array([[67,  7, 26, 18, 85],
       [85, 29, 87, 19, 55]])

In [43]:
# if we have to find the max value of an array we a can call max()
ranno= np.random.randint(0,100,20).reshape(4,5)

In [44]:
ranno

array([[65, 61, 30, 33, 27],
       [ 4, 62, 67, 57, 85],
       [61,  5, 15, 10, 25],
       [49, 28,  4, 63, 33]])

In [45]:
ranno.max()

85

In [47]:
# min value of an array
ranno.min()

4

In [48]:
# if we want the index of the max and min value of an array not the value
ranno.argmax()

9

In [49]:
ranno.argmin()

5

In [50]:
# if we want to find the shape of the array
# we not adding paraenthesis as we calling the attribute not function
ranno.shape

(4, 5)

In [52]:
# to find the data type of the array 
# calling attribute 
ranno.dtype

dtype('int64')

### numpy indexing and selection

In [54]:
arr = np.arange(1,10)

In [55]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
arr[4]

5

In [57]:
arr[2:6]

array([3, 4, 5, 6])

In [58]:
# everything from very starting
arr[:7]

array([1, 2, 3, 4, 5, 6, 7])

In [59]:
# everything beyond 4 index till last
arr[4:]

array([5, 6, 7, 8, 9])

In [61]:
# here one thing that the numpy arry is different with normal list is that --->>> broadcast
# it just assign the index b/w the value given
arr[0:5]=100

In [62]:
arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9])

In [4]:
arr1= np.random.randint(0,20,10)

In [5]:
arr1

array([ 7, 17, 12,  2, 18,  3, 19,  7,  2,  4])

In [67]:
# it doesn't copied to new data but it only give the reference in numpy array 
# this numpy do to resolve the memory issue by large array
# thus any changes in this array changes in the original array 

slice_of_array = arr1[0:6]

In [68]:
slice_of_array

array([15,  5,  9,  8,  4,  5])

In [69]:
# if we broadcast in the slice of array 

slice_of_array[:]= 89

In [70]:
slice_of_array

array([89, 89, 89, 89, 89, 89])

In [71]:
# but if we call back the array 
# the slice of array doesn't only change to but also the original array
arr1

array([89, 89, 89, 89, 89, 89,  0, 10, 19, 13])

In [6]:
# if we want copy of this array not the reference then we can call the copy function 
# it makes the copy of the array
arr_copy = arr1.copy()

In [7]:
arr_copy

array([ 7, 17, 12,  2, 18,  3, 19,  7,  2,  4])

In [8]:
arr_copy[:] = 100

In [9]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [10]:
arr1

array([ 7, 17, 12,  2, 18,  3, 19,  7,  2,  4])

In [11]:
arr_2D = np.array([[1,34,4],[3,545,56],[23,43545,32]])

In [12]:
arr_2D

array([[    1,    34,     4],
       [    3,   545,    56],
       [   23, 43545,    32]])

In [ ]:
# we have two methods to grab the value from it 
# 1. [][] (double brackets )
# 2. [,] square brackets  separated by comma


In [19]:
# if we have to grab 545
# arr_2D [row][column]
arr_2D[1][1]

545

In [20]:
arr_2D[1,1]

545

In [15]:
# gives entire row
arr_2D[0]

array([ 1, 34,  4])

In [24]:
# to get the certain section of the array 
# if i have to grab top right corner

# arr_2D[row  -> everthing from start to row 2 (exclusive 2), column -> grab from index 1 to end]
arr_2D[:2,1:]

array([[ 34,   4],
       [545,  56]])

In [25]:
arr_2D

array([[    1,    34,     4],
       [    3,   545,    56],
       [   23, 43545,    32]])

In [26]:
arr_2D[1:,1:]

array([[  545,    56],
       [43545,    32]])

### conditional selection

In [27]:
arr = np.arange(11)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
# if a compare the array with any value then we get the boolean array 
bool_arr= arr>5

In [31]:

bool_arr
# we use this boolean array to conditional selection

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [32]:
arr[bool_arr]
# those index which are true in boolean array we can fetch those values

array([ 6,  7,  8,  9, 10])

In [33]:
# or we can direclty do this
arr[arr >5]

array([ 6,  7,  8,  9, 10])

In [34]:
arr[arr<3]

array([0, 1, 2])

### numpy operation

1. array with array operation
2. array with scalars
3. universal array functions

In [35]:
import numpy as  np

In [36]:
arr= np.arange(0,11)

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
# adding two arrays togeather
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [39]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [40]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [41]:
# scalar operation add a value to every element
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [42]:
# in this case any value /0 doesn't give the array error but just only give the warning
# and the first element is changes to nan
arr/arr

/tmp/ipykernel_2575/1862401812.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [43]:
# in this case we get the infinity (inf) inspite of error which make code more robust
1/arr

/tmp/ipykernel_2575/255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [44]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [45]:
# if we have to take the square root of every element 
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [46]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [48]:
np.max(arr)

10

In [49]:
np.sign(arr)

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])